export const SEARCH_FOUCSED = 'header/SEARCH_FOCUSED'
export const SEARCH_BLURED = 'header/SEARCH_BLURED'
export const CHANGE_LIST = 'header/CHANGE_LIST'
export const MOUSE_ENTER = 'header/MOUSE_ENTER'
export const MOUSE_LEAVE = 'header/MOUSE_LEAVE'
export const CHANGE_PAGE = 'header/CHANGE_PAGE'